export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const GET_VARIANTS = "GET_VARIANTS";
export const ADD_VARIANTS = "ADD_VARIANTS";
export const GET_ORDERS = "GET_ORDERS";
export const ADD_ORDERS = "ADD_ORDERS";
export const UPDATE_ORDERS = "UPDATE_ORDERS";
export const DELETE_ORDERS = "DELETE_ORDERS";
export const CREATE_USERS = "ADD_USERS";
export const LOGIN_USERS = "LOGIN_USERS";
export const GET_USERS = "GET_USERS";

//Organizations and Teams

export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const ADD_ORGANIZATIONS = "ADD_ORGANIZATIONS";
export const UPDATE_ORGANIZATIONS = "UPDATE_ORGANIZATIONS";
export const DELETE_ORGANIZATIONS = "DELETE_ORGANIZATIONS";

export const ADD_TEAMS = "ADD_TEAMS";


// bill 

export const FILTER_INVOICES = 'FILTER_INVOICES';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const ADD_INVOICE = 'ADD_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const MARK_INVOICE_PAID = 'MARK_INVOICE_PAID';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const CANCEL_INVOICE_EDIT = 'CANCEL_INVOICE_EDIT';
export const LOAD_INVOICES_DATA = 'LOAD_INVOICES_DATA';
export const ENABLE_DARK_MODE = 'ENABLE_DARK_MODE';
export const DISABLE_DARK_MODE = 'DISABLE_DARK_MODE';
