export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const ADD_VARIANTS = "ADD_VARIANTS";
export const GET_VARIANTS = "GET_VARIANTS";
export const GET_VARIANTS_FIELD = "GET_VARIANTS_FIELD";